#pragma once

#define MESSAGE_BUFFER 1024
#define MAX_MESSAGES_COUNT 100
#define USERNAME_BUFFER 16
#define SERVER_IP_BUFFER 16
#define SERVER_PORT_BUFFER 8

#define LOGIN_WIDTH 30
#define LOGIN_HEIGHT 3
#define LOGIN_PADDING 13
#define CHAT_MESSAGE_WIDTH 60
#define CHAT_MESSAGE_HEIGHT 8
#define CHAT_MESSAGES_PADDING 4